const ICO = [
  {
    inputs: [
      { internalType: "address", name: "_Ecosystem", type: "address" },
      { internalType: "address", name: "_Treasury", type: "address" },
      { internalType: "address", name: "_Team", type: "address" },
      { internalType: "address", name: "_Marketing", type: "address" },
      { internalType: "address", name: "_AdvisorCommittee", type: "address" },
      { internalType: "address", name: "_tokenAddress", type: "address" },
      { internalType: "address", name: "_receiverAddress", type: "address" },
      { internalType: "address", name: "_usdt", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "claimedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "remainingClaimedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "nextClaimTimeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "claimCount",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "phaseNo",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "phaseTransactionCounter",
        type: "uint16",
      },
    ],
    name: "BuyerUserClaimToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "fromPhase",
        type: "uint8",
      },
      { indexed: false, internalType: "uint8", name: "toPhase", type: "uint8" },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokensMoved",
        type: "uint256",
      },
    ],
    name: "PhaseChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "claimedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "remainingClaimedAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "nextClaimTimeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "claimCount",
        type: "uint16",
      },
    ],
    name: "RegisterUserClaimedToken",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "buyAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "price",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "timeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "nextClaimTimeStamp",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "phaseNo",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "phaseTransactionCounter",
        type: "uint16",
      },
      { indexed: false, internalType: "uint8", name: "buyType", type: "uint8" },
    ],
    name: "TokensBought",
    type: "event",
  },
  {
    inputs: [],
    name: "AdvisorCommittee",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ETHOracle",
    outputs: [
      { internalType: "contract OracleWrapper", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Ecosystem",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Marketing",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Team",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Treasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "USDTOracle",
    outputs: [
      { internalType: "contract OracleWrapper", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "_type", type: "uint8" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "buyTokens",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint16", name: "_phaseNo", type: "uint16" },
      {
        internalType: "uint16",
        name: "_phaseTransactionCounter",
        type: "uint16",
      },
    ],
    name: "buyerUserClaimToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint16", name: "_phaseNo", type: "uint16" },
      {
        internalType: "uint16",
        name: "_phaseTransactionCounter",
        type: "uint16",
      },
    ],
    name: "buyerUserTokensToBeClaimed",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint16", name: "", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "_type", type: "uint8" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "calculateTokens",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint8", name: "", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "changePhase",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "defaultPhase",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "icoFirstPhaseStartTime",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_to", type: "address" }],
    name: "isRegisterUser",
    outputs: [
      { internalType: "bool", name: "isValidUser", type: "bool" },
      { internalType: "uint256", name: "totalTokenAmount", type: "uint256" },
      { internalType: "uint256", name: "claimedAmount", type: "uint256" },
      { internalType: "uint256", name: "claimableAmount", type: "uint256" },
      { internalType: "uint16", name: "claimCount", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "monthTime",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "phaseInfo",
    outputs: [
      { internalType: "uint256", name: "tokenSold", type: "uint256" },
      { internalType: "uint256", name: "tokenLimit", type: "uint256" },
      { internalType: "uint32", name: "price", type: "uint32" },
      { internalType: "uint16", name: "lockingPeriod", type: "uint16" },
      {
        internalType: "uint16",
        name: "monthlyVestingPercentage",
        type: "uint16",
      },
      { internalType: "uint16", name: "totalClaimCounter", type: "uint16" },
      { internalType: "bool", name: "isComplete", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "receiverAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "registerUserClaimTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "registerUserMapping",
    outputs: [
      { internalType: "uint256", name: "totalAmount", type: "uint256" },
      { internalType: "uint256", name: "claimedAmount", type: "uint256" },
      { internalType: "uint32", name: "lockingPeriod", type: "uint32" },
      {
        internalType: "uint16",
        name: "monthlyVestingPercentage",
        type: "uint16",
      },
      { internalType: "uint16", name: "totalClaimCounter", type: "uint16" },
      { internalType: "uint16", name: "claims", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_to", type: "address" }],
    name: "registerUserTokensToBeClaimed",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint16", name: "", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "sendLeftoverTokensToReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_icoFirstPhaseStartTime",
        type: "uint32",
      },
    ],
    name: "setFirstPhaseStartTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "startTime",
    outputs: [{ internalType: "uint32", name: "", type: "uint32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenInstance",
    outputs: [
      { internalType: "contract IERC20Metadata", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalPhases",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalTokenSold",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalUSDTRaised",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdtInstance",
    outputs: [
      { internalType: "contract IERC20Metadata", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint32", name: "", type: "uint32" },
    ],
    name: "userPhaseCounter",
    outputs: [{ internalType: "uint16", name: "", type: "uint16" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint32", name: "", type: "uint32" },
      { internalType: "uint128", name: "", type: "uint128" },
    ],
    name: "userPhaseTransactionDetails",
    outputs: [
      { internalType: "uint256", name: "amount", type: "uint256" },
      { internalType: "uint256", name: "claimAmount", type: "uint256" },
      { internalType: "uint32", name: "startTime", type: "uint32" },
      { internalType: "uint16", name: "totalClaimCounter", type: "uint16" },
      { internalType: "uint16", name: "claims", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
];
export default ICO;
